### ISSUE TITLE
[Bug]: Input's placeholder color not good with @layer on chromium browsers

### ISSUE THREAD

**Issue by CarolineSabourin-Jean** [gsoft-inc/ov-igloo-ui#662] opened 2024-01-29 21:39 UTC
### What happened?

As we can see here, the input's placeholder color is overriden by the browser because of the layer.
![image](https://github.com/gsoft-inc/ov-igloo-ui/assets/25105785/79387126-0a65-4384-9a7e-091cd8c4354c)

It is a bug with chromium browsers. On firefox, for example, it is fine.

So to fix it, you can extract the ::placeholder color out of the layer. Here's an exemple: https://dev.azure.com/officevibe/Officevibe/_git/Officevibe/pullrequest/28951?_a=files&path=/portal/packages/components/inputs/input/input.scss

The problem occurs only with the html input element. I don't know if you use it somewhere else than in the Input component, but if so, you'll have to fix it there too.

### Component

Input

### Component Version

2.2.0

### Which browsers are you seeing the problem on?

Chrome, Microsoft Edge

**Comment by fraincs** [comment] 2024-01-31 02:54
Did you find an opened issue regarding this somewhere? I can reproduce the bug and was expecting to find reports on the internet regarding this issue, to no avail.

**Comment by CarolineSabourin-Jean** [comment] 2024-01-31 13:35
No I don't, sorry.

I see in your PR that you have done the same fix for the textearea. Personally, I tested it and wasn't able the reproduce the bug of the input on the textarea. Did you have the bug also with the textarea?

**Comment by fraincs** [comment] 2024-01-31 15:03
You are right as textarea placeholder uses the user agent stylesheet where the input placeholder receives an injected stylesheet, I'd like to investigate further as this seems like a weird difference.

<img width="554" alt="image" src="https://github.com/gsoft-inc/ov-igloo-ui/assets/361632/d950f395-580b-4a17-9788-03c07bc3ad46">

**Comment by fraincs** [comment] 2024-01-31 16:21
From the look of it the issue is caused by a third-party extension. There's a way to fix this by adding !important to the declaration inside the @layer, that said it would be hard to override by the users. This raises another question which is should we give extensions free will on inputs? If a user uses a third party extension their expectations is that we respect what the extension does to the input.

**Comment by fraincs** [comment] 2024-01-31 18:43
Closing the issue as it's not something we are going to do given the latest developments.

**Closed by fraincs** 2024-01-31 18:43 UTC
Labels: bug
